pipeline:
  restore_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    restore: true
    mount:
      - /drone/pip-cache
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event:
        - push
        - pull_request
        - tag
  build:
    image: fusionapp/base
    pull: true
    environment:
      - PIP_CACHE_DIR=/drone/pip-cache
    commands:
      - mkdir -p $PIP_CACHE_DIR
      - >
        /appenv/bin/pip wheel
        --wheel-dir wheelhouse
        --requirement requirements.txt .
    when:
      event:
        - push
        - pull_request
        - tag
  rebuild_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    rebuild: true
    mount:
      - /drone/pip-cache
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  flush_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    flush: true
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  publish:
    image: plugins/ecr
    dockerfile: docker/entropy.docker
    region: eu-west-1
    registry: 801493518741.dkr.ecr.eu-west-1.amazonaws.com
    repo: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/entropy
    tags:
      - ${DRONE_BRANCH}
      - git-${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
    secrets:
      - ecr_access_key
      - ecr_secret_key
  deploy:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: entropy/entropy
    docker_image: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/entropy:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 240
    when:
      event: deployment
      environment: production
    secrets:
      - rancher_access_key
      - rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
  slack_production:
    image: plugins/slack
    secrets:
      - slack_webhook
    channel: production
    when:
      event: deployment
      environment: production
      status:
        - success
        - failure
branches:
  - master
  - staging
  - trying
